---
output: pdf_document
geometry: margin = 0.75in
header-includes: 
  - \usepackage{booktabs}
  - \usepackage{nopageno}
  - \usepackage{longtable}
  - \usepackage{caption}
  - \captionsetup{labelformat = empty, justification = justified}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = FALSE, cache = FALSE, comment = "", warning = FALSE, message = FALSE,
  fig.height = 1.8, fig.width = 2.5, fig.align = "center"
)
```


\large Table: Binomial probability mass function (PMF) probabilities
\vspace{0.2in}


```{r results = "asis", message = FALSE}
suppressWarnings(library(xtable))
suppressWarnings(library(magrittr))


x <- 0:input$binom_n_custom
p <- input$binom_p_custom %>%
  strsplit(split = "\n|,") %>%    # split if see comma or new line
      unlist() %>%
      as.numeric() %>%
      na.omit()    # remove any NAs

x_p_pairs <- expand.grid(x = x, p = p)

probs <- Map(dbinom, 
  x = x_p_pairs$x,
  size = input$binom_n_custom,
  prob = x_p_pairs$p
)
table_probs <- probs %>% 
  unlist() %>%
  round(input$round_digits) %>%
  matrix(nrow = length(x), byrow = FALSE)

table_probs_new <- cbind.data.frame(x, table_probs)

col_names <- formatC(signif(p, 2), format = "f", digits = 2)
col_names_centered <- paste0("\\multicolumn{1}{c}{", col_names, "}")

colnames(table_probs_new) <- c("xp", col_names_centered)


if (input$drop_lead_zeros) {
  table_probs_new[, -1] <- apply(table_probs_new[, -1], 2, 
    function(.) gsub("^0.", ".", sprintf(paste0("%.", input$round_digits, "f"), .))
  )

  colnames(table_probs_new) <- gsub("\\{0.", "\\{.", colnames(table_probs_new))
}


format_col_names <- function(x) {
  x <- gsub("xp", "$\\x \\\\, \\\\backslash \\\\, \\p$", x)
  x
}


add_to_row <- list(
  pos = list(0),
  command = paste0("\\hline\n\\endhead\n",
    "\\hline\n",
    "\\multicolumn{", length(input$binom_p_custom) + 1, "}{l}",
    "{\\small Continued on next page}\n",
    "\\endfoot\n",
    "\\endlastfoot\n"
  )
)


print(
  xtable::xtable(table_probs_new, 
    digits = c(0, 0, rep(input$round_digits, length(p))),
    align = c("c|", "c|", rep("c", length(p))),
    type = "latex",
  ),
  include.rownames = FALSE,
  sanitize.colnames.function = format_col_names,
  comment = FALSE,
  booktabs = TRUE,
  hline.after = c(-1, nrow(table_probs_new)),    # -1 for horiz. line above table
  add.to.row = add_to_row,
  tabular.environment = "longtable"    # in case table spans multiple pages
)
```



