---
output: pdf_document
geometry: margin = 0.75in
header-includes: 
  - \usepackage{booktabs}
  - \usepackage{nopageno}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = FALSE, cache = FALSE, comment = "", warning = FALSE, message = FALSE,
  fig.height = 1.4, fig.width = 2.2, fig.align = "center"
)
```


\large Table: Critical values of $t$
\vspace{0.2in}


```{r}
library(ggplot2); theme_set(theme_classic())
library(xtable)
library(magrittr)


shaded_cutoff <- qt(p = 0.08, df = 4, lower.tail = FALSE)
x_right <- seq(shaded_cutoff, 4, by = 0.001)
shaded_right <- data.frame(x = x_right, y = dt(x_right, df = 4))

ggplot(data.frame(x = c(-4, 4))) +
  geom_area(data = shaded_right, aes(x = x, y = y), fill = "darkgray") +
  stat_function(fun = dt, args = list(df = 4), lwd = 0.7) +
  geom_hline(yintercept = 0, lwd = 0.4) +
  geom_segment(x = 0, y = 0, xend = 0, yend = dt(0, df = 4)/10, lwd = 0.4) +
  geom_segment(x = shaded_cutoff, y = 0, xend = shaded_cutoff, 
    yend = dt(shaded_cutoff, df = 4), lwd = 0.4
  ) +
  geom_segment(
    x = 2.95, y = 1.2*dt(shaded_cutoff, df = 4), 
    xend = 2, yend = dt(shaded_cutoff, df = 4)/4.5, 
    arrow = arrow(length = unit(0.1, "cm"), type = "closed"),
    size = 0.3
  ) +
  annotate(geom = "text",
    x = 3.2, y = 1.5*dt(shaded_cutoff, df = 4),
    label = "alpha",
    parse = TRUE, size = 3
  ) +
  scale_x_continuous(limits = c(-4, 4), breaks = c(0, shaded_cutoff), 
    labels = c(0, expression(italic(t)[alpha]))
  ) +
  labs(x = "", y = "") +
  theme(
    axis.text.y = element_blank(), axis.ticks = element_blank(),
    axis.line = element_blank(), axis.title.x = element_text(size = 12),
    axis.text.x = element_text(size = 12, color = "black", margin = margin(t = -2))
  )
```


\vspace{0.1in}


```{r results = "asis"}

### critical t values
alpha <- c(0.25, 0.1, 0.05, 0.025, 0.01, 0.005, 0.001, 0.0005)
df <- c(1:30, 40, 50, 60, 80, 100, 1e3, 1e6)

# lower tail = FALSE below
alpha_df_pairs <- expand.grid(crit_df = df, crit_alpha = alpha)

crit_values <- Map(qt, 
  p = alpha_df_pairs$crit_alpha, 
  df = alpha_df_pairs$crit_df, 
  lower.tail = FALSE
)

table_values <- crit_values %>% 
  unlist() %>%
  round(input$round_digits) %>%
  matrix(nrow = length(df), byrow = FALSE)

table_values_new <- cbind.data.frame(df, table_values)
table_values_new[nrow(table_values_new), 1] <- "infty"
col_names <- c("$df$", "$t_{0.25}$", "$t_{0.10}$", "$t_{0.05}$", "$t_{0.025}$", 
  "$t_{0.01}$", "$t_{0.005}$", "$t_{0.001}$", "$t_{0.0005}$"
)
colnames(table_values_new) <- paste0("\\multicolumn{1}{c}{", col_names, "}")


if (input$drop_lead_zeros) {
  table_values_new[, -1] <- apply(table_values_new[, -1], 2, 
    function(.) gsub("^0.", ".", sprintf(paste0("%.", input$round_digits, "f"), .))
  )
  
  colnames(table_values_new) <- gsub("\\{0.", "\\{.", colnames(table_values_new))
}


format_text <- function(x) {
  x <- gsub("infty", "$\\\\infty$", x)
  x
}


addtorow <- list(
  pos = as.list(seq(4, 29, by = 5)), 
  command = rep("\\vspace{0.08in}", 6)
)


print(
  xtable::xtable(table_values_new, 
    digits = c(0, 0, rep(input$round_digits, 8)),
    align = c("c|", "c|", rep("r", 8)),
    type = "latex"
  ), 
  include.rownames = FALSE,
  sanitize.text.function = format_text,
  add.to.row = addtorow,
  comment = FALSE,
  booktabs = TRUE
)
```



