
library(shiny)


shinyUI(navbarPage("Statistical Tables Generator",
  
  ##### Create Table tabpanel
  ############################################################
  tabPanel("Create Table", icon = icon("table"),
    
    column(3,
      wellPanel(
        radioButtons("dist", "Distributions", 
          choices = c("Standard Normal" = "norm", "t" = "t", 
            "Chi-square" = "chisq", "F" = "f", "Binomial" = "binomial", 
            "Poisson" = "poisson"
          ), 
          selected = "norm"
        ),
        
        conditionalPanel(
          condition = "input.dist == 'norm'", 
          
          radioButtons("norm_area", "Shaded Area", 
            choices = c("Left" = "left", "Middle" = "middle", "Right" = "right"),
            selected = "left"
          )
        ),
        
        conditionalPanel(
          condition = "input.dist == 't'",
          
          radioButtons("t_area", "Shaded Area", 
            choices = c("Right Tail" = "right", "Middle" = "middle"),
            selected = "right"
          )
        ),
        
        conditionalPanel(
          condition = "input.dist == 'f'",
          
          radioButtons("alpha_f", "Alpha (Right Tail Only)", 
            choices = c("0.10 (10%)" = "a10", "0.05 (5%)" = "a05", 
            "0.025 (2.5%)" = "a025", "0.01 (1%)" = "a01", "0.001 (0.1%)" = "a001"
            ),
            selected = "a05"
          )
        ),
        
        conditionalPanel(
          condition = "input.dist == 'binomial'",
          
          radioButtons("binom_area", "Shaded Area",
            choices = c("PMF" = "binom_pmf", "CDF" = "binom_cdf"),
            selected = "binom_pmf"
          ),
          
          checkboxInput("binom_custom_table", 
            "Make Custom Table: Choose # Trials and Probabilities", 
            value = FALSE
          ),
          
          conditionalPanel(
            condition = "input.binom_custom_table",
            
            numericInput("binom_n_custom", "# Trials / Sample Size", 
              value = 10
            ),
            tags$head(tags$style(type = "text/css", 
              "#binom_n_custom{width: 100px;}"
            )),
            
            strong("Probabilities / Proportions"),
            p("(separate by commas)"),
            textAreaInput("binom_p_custom", NULL, value = "0.28, 0.72, 0.91")
          )
        ),
        
        conditionalPanel(
          condition = "input.dist == 'poisson'",
          
          radioButtons("pois_area", "Shaded Area",
            choices = c(
              "PMF, rates = 0.2 to 10 in increments of 0.2" = "pois_pmf_2",
              "PMF, rates = 0.5 to 20 in increments of 0.5" = "pois_pmf_5",
              "CDF, rates = 0.2 to 10 in increments of 0.2" = "pois_cdf_2",
              "CDF, rates = 0.5 to 20 in increments of 0.5" = "pois_cdf_5"
            ),
            selected = "pois_pmf_2"
          )
        )
      )
    ),
    
    column(4,
      wellPanel(
        uiOutput("digits_input"),
        
        # formatting for numeric input belonging to uiOutput above
        tags$head(tags$style(type = "text/css", "#round_digits{width: 100px;}")),
        
        
        conditionalPanel(
          condition = "input.dist == 'norm'",
          
          checkboxInput("include_crit_z_table", "Include Table with Common 
            Critical Z-scores", value = FALSE
          )
        ),
        
        checkboxInput("drop_lead_zeros", "Drop Leading Zeros Before Decimals", 
          value = FALSE
        ),
        
        downloadButton("download_table", "Download Table", 
          class = "btn btn-primary"
        ),
        br(),
        br(),
        
        p("Note: It will take a few seconds to generate the table.")
      )
    )
  ),

  
  
  ##### About tabpanel
  ############################################################
  tabPanel("About", icon = icon("info-circle"),
    
    column(4,
      h4("The information below will be updated after the completion of the blind
        review process."
      ),
      br(),
      
      # information about the developer
      h4("Developer"),
      p("This tool was developed by Anonymous."),
      br(),
      
      # information about the app
      h4("About the App"),
      HTML("The app allows users to create statistical tables associated with
        common probability distributions. <b>Anyone may freely download, 
        distribute, and/or use any tables generated by this app without needing 
        to cite the developer of the app and without fear of copyright 
        infringement. </b>"
      ),
      br(),
      br(),
      
      # contact info
      h4("Contact"),
      p("Email: Anonymous"),
      br(),
      br(),
      
      # copyright statement
      p("Copyright \uA9 2020-2021 by Anonymous."),
      p("The license statement can be found", 
        a("here.", href = "https://opensource.org/licenses/MIT", target = "_blank")
      )
    )
  )
))



